package razorclaw.linguistic.pos;

public enum OpenCalaisEntityTag 
{
	ANNIVERSARY(EntityType.EVENT),
	CITY(EntityType.PLACE),
	COMPANY(EntityType.ORGANISATION),
	CONTINENT(EntityType.PLACE),
	COUNTRY(EntityType.PLACE),
	CURRENCY(EntityType.MEASURE),
	EMAILADDRESS(EntityType.IDENTIFIER),
	FACILITY(EntityType.PRODUCT),
	FAXNUMBER(EntityType.IDENTIFIER),
	HOLIDAY(EntityType.PRODUCT),
	INDUSTRYTERM(EntityType.IDENTIFIER),
	MARKETINDEX(EntityType.MEASURE),
	MEDICALCONDITION(EntityType.PRODUCT),
	MEDICALTREATMENT(EntityType.PRODUCT),
	MOVIE(EntityType.PRODUCT),
	MUSICALBUM(EntityType.PRODUCT),
	MUSICGROUP(EntityType.PRODUCT),
	NATURALFEATURE(EntityType.PLACE),
	OPERATINGSYSTEM(EntityType.PRODUCT),
	ORGANIZATION(EntityType.ORGANISATION),
	PERSON(EntityType.PERSON),
	PHONENUMBER(EntityType.IDENTIFIER),
	PRODUCT(EntityType.PRODUCT),
	PROGRAMMINGLANGUAGE(EntityType.PRODUCT),
	PROVINCEORSTATE(EntityType.PLACE),
	PUBLISHEDMEDIUM(EntityType.PRODUCT),
	RADIOPROGRAM(EntityType.PRODUCT),
	RADIOSTATION(EntityType.PRODUCT),
	REGION(EntityType.PLACE),
	SPORTSEVENT(EntityType.EVENT),
	SPORTSGAME(EntityType.PRODUCT),
	SPORTSLEAGUE(EntityType.PRODUCT),
	TVSHOW(EntityType.PRODUCT),
	TVSTATION(EntityType.ORGANISATION),
	TECHNOLOGY(EntityType.PRODUCT),
	URL(EntityType.IDENTIFIER),
	ENTERTAINMENTAWARDEVENT(EntityType.EVENT),
	ACQUISITION(EntityType.EVENT),
	ALLIANCE(EntityType.EVENT),
	ANALYSTEARNINGSESTIMATE(EntityType.EVENT),
	ANALYSTRECOMMENDATION(EntityType.EVENT),
	ARREST(EntityType.EVENT),
	BANKRUPTCY(EntityType.EVENT),
	BONUSSHARESISSUANCE(EntityType.EVENT),
	BUSINESSRELATION(EntityType.EVENT),
	BUYBACKS(EntityType.EVENT),
	COMPANYACCOUNTINGCHANGE(EntityType.EVENT),
	COMPANYEARNINGSANNOUNCEMENT(EntityType.EVENT),
	COMPANYEARNINGSGUIDANCE(EntityType.EVENT),
	COMPANYEXPANSION(EntityType.EVENT),
	COMPANYFORCEMAJEURE(EntityType.EVENT),
	COMPANYINVESTMENT(EntityType.EVENT),
	COMPANYLABORISSUES(EntityType.EVENT),
	COMPANYLAYOFFS(EntityType.EVENT),
	COMPANYLEGALISSUES(EntityType.EVENT),
	COMPANYLISTINGCHANGE(EntityType.EVENT),
	COMPANYMEETING(EntityType.EVENT),
	COMPANYNAMECHANGE(EntityType.EVENT),
	COMPANYREORGANIZATION(EntityType.EVENT),
	COMPANYRESTATEMENT(EntityType.EVENT),
	CONFERENCECALL(EntityType.EVENT),
	CONVICTION(EntityType.EVENT),
	CREDITRATING(EntityType.EVENT),
	DEBTFINANCING(EntityType.EVENT),
	DELAYEDFILING(EntityType.EVENT),
	DIVIDEND(EntityType.EVENT),
	EMPLOYMENTCHANGE(EntityType.EVENT),
	ENVIRONMENTALISSUE(EntityType.EVENT),
	EXTINCTION(EntityType.EVENT),
	FDAPHASE(EntityType.EVENT),
	INDICTMENT(EntityType.EVENT),
	IPO(EntityType.EVENT),
	JOINTVENTURE(EntityType.EVENT),
	MANMADEDISASTER(EntityType.EVENT),
	MERGER(EntityType.EVENT),
	MOVIERELEASE(EntityType.EVENT),
	MUSICALBUMRELEASE(EntityType.EVENT),
	NATURALDISASTER(EntityType.EVENT),
	PATENTFILING(EntityType.EVENT),
	PATENTISSUANCE(EntityType.EVENT),
	PERSONTRAVEL(EntityType.EVENT),
	POLITICALRELATIONSHIP(EntityType.EVENT),
	PRODUCTISSUES(EntityType.EVENT),
	PRODUCTRECALL(EntityType.EVENT),
	PRODUCTRELEASE(EntityType.EVENT),
	SOCIALTAGS(EntityType.EVENT),
	SECONDARYISSUANCE(EntityType.EVENT),
	PERSONCOMMUNICATION(EntityType.EVENT),
	STOCKSPLIT(EntityType.EVENT),
	TRIAL(EntityType.EVENT),
	UNKNOWN(EntityType.UNKNOWN),
	DAY(EntityType.DATE),
	MONTH(EntityType.DATE);
	
	private EntityType _type;
	
	private OpenCalaisEntityTag(EntityType type)
	{
		_type = type;
	}
	
	public EntityType getEntityType()
	{
		return _type;
	}
	
	public static OpenCalaisEntityTag load(String tag)
	{
		try
		{
			return (OpenCalaisEntityTag) Enum.valueOf(OpenCalaisEntityTag.class, tag);
		}
		catch (IllegalArgumentException iae)
		{
			return OpenCalaisEntityTag.UNKNOWN;
		}
	}
}
